name: CI
on:
  push:
  pull_request:
jobs:
    lint-test:
      runs-on: ubuntu-latest
      steps:
      - name: CheckOut
        uses: actions/checkout@v4
      - name: SetUp Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...
      - name: Vet
        run: go vet ./...
      - name: Format-Check
        run: test -z "$(gofmt -l .)"